DO $$ DECLARE v_uid uuid; v_pid uuid; v_ids uuid[];
BEGIN SELECT id INTO v_uid FROM auth.users LIMIT 1;
IF NOT EXISTS (SELECT 1 FROM public.partenaires WHERE company_name = 'Kwenda Test Fleet') THEN INSERT INTO public.partenaires (user_id, display_name, company_name, email, phone_number, business_type, address, verification_status, is_active, commission_rate, city, country, service_areas) VALUES (COALESCE(v_uid, gen_random_uuid()), 'Test Fleet Manager', 'Kwenda Test Fleet', 'testfleet@kwenda.cd', '+243900000000', 'fleet_management', 'Avenue Kwenda, Gombe', 'verified', true, 15.00, 'Kinshasa', 'RDC', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi']); END IF;
SELECT id INTO v_pid FROM public.partenaires WHERE company_name = 'Kwenda Test Fleet' LIMIT 1;
SELECT array_agg(id ORDER BY sort_order) INTO v_ids FROM public.rental_vehicle_categories LIMIT 7;
DELETE FROM public.rental_vehicles WHERE partner_id = v_pid;
INSERT INTO public.rental_vehicles (partner_id, category_id, name, brand, model, year, vehicle_type, fuel_type, transmission, seats, daily_rate, hourly_rate, weekly_rate, security_deposit, features, images, city, available_cities, comfort_level, equipment, license_plate, is_active, is_available, moderation_status) VALUES
(v_pid, v_ids[1], 'Toyota Yaris Eco', 'Toyota', 'Yaris', 2022, 'Citadine', 'Essence', 'Automatique', 5, 120000, 15000, 700000, 200000, '["Climatisation","Bluetooth","USB"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'standard', '["air_conditioning","bluetooth","usb_port"]'::jsonb, 'TEST-CAT1-001', true, true, 'approved'),
(v_pid, v_ids[1], 'Hyundai i10 Compact', 'Hyundai', 'i10', 2023, 'Citadine', 'Essence', 'Manuelle', 5, 110000, 14000, 650000, 180000, '["Climatisation","Radio FM"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'standard', '["air_conditioning","radio"]'::jsonb, 'TEST-CAT1-002', true, true, 'approved'),
(v_pid, v_ids[2], 'Toyota Camry Prestige', 'Toyota', 'Camry', 2023, 'Berline', 'Hybride', 'Automatique', 5, 200000, 25000, 1200000, 400000, '["Climatisation Auto","GPS","Sièges Cuir"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'premium', '["air_conditioning","gps","leather_seats","bluetooth"]'::jsonb, 'TEST-CAT2-001', true, true, 'approved'),
(v_pid, v_ids[2], 'Honda Accord Executive', 'Honda', 'Accord', 2022, 'Berline', 'Essence', 'Automatique', 5, 190000, 24000, 1150000, 380000, '["Climatisation","GPS","Apple CarPlay"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'premium', '["air_conditioning","gps","apple_carplay"]'::jsonb, 'TEST-CAT2-002', true, true, 'approved'),
(v_pid, v_ids[3], 'Mercedes S-Class Luxury', 'Mercedes-Benz', 'S-Class', 2024, 'Berline Luxe', 'Hybride', 'Automatique', 5, 800000, 100000, 4800000, 1500000, '["Climatisation 4 Zones","GPS Premium","Sièges Massants"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'luxury', '["air_conditioning","gps","massage_seats","panoramic_roof","premium_sound"]'::jsonb, 'TEST-CAT3-001', true, true, 'approved'),
(v_pid, v_ids[3], 'BMW 7 Series Executive', 'BMW', '7 Series', 2023, 'Berline Luxe', 'Diesel', 'Automatique', 5, 750000, 95000, 4500000, 1400000, '["Climatisation Auto","GPS","Sièges Ventilés"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'luxury', '["air_conditioning","gps","ventilated_seats","rear_screens"]'::jsonb, 'TEST-CAT3-002', true, true, 'approved'),
(v_pid, v_ids[4], 'Toyota Land Cruiser V8', 'Toyota', 'Land Cruiser', 2023, 'SUV', 'Diesel', 'Automatique', 7, 350000, 45000, 2100000, 700000, '["4x4","Climatisation","GPS","7 Places"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'premium', '["air_conditioning","gps","backup_camera","leather_seats","four_wheel_drive"]'::jsonb, 'TEST-CAT4-001', true, true, 'approved'),
(v_pid, v_ids[4], 'Nissan Patrol Platinum', 'Nissan', 'Patrol', 2022, 'SUV', 'Diesel', 'Automatique', 7, 320000, 42000, 1920000, 650000, '["4x4","Climatisation","GPS"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'premium', '["air_conditioning","gps","leather_seats","sunroof"]'::jsonb, 'TEST-CAT4-002', true, true, 'approved'),
(v_pid, v_ids[5], 'Mercedes Sprinter Cargo', 'Mercedes-Benz', 'Sprinter', 2023, 'Utilitaire', 'Diesel', 'Manuelle', 3, 500000, 65000, 3000000, 800000, '["Grande Capacité","Climatisation","GPS"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'standard', '["air_conditioning","gps","cargo_space"]'::jsonb, 'TEST-CAT5-001', true, true, 'approved'),
(v_pid, v_ids[5], 'Ford Transit Pro', 'Ford', 'Transit', 2022, 'Utilitaire', 'Diesel', 'Manuelle', 3, 450000, 60000, 2700000, 750000, '["Volume 12m³","Climatisation","Radio"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'standard', '["air_conditioning","radio","cargo_space"]'::jsonb, 'TEST-CAT5-002', true, true, 'approved'),
(v_pid, v_ids[6], 'Toyota Hiace Commuter', 'Toyota', 'Hiace', 2023, 'Minibus', 'Diesel', 'Manuelle', 14, 600000, 75000, 3600000, 1000000, '["14 Places","Climatisation Centrale"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'standard', '["air_conditioning","luggage_rack","passenger_seats"]'::jsonb, 'TEST-CAT6-001', true, true, 'approved'),
(v_pid, v_ids[6], 'Nissan Urvan Premium', 'Nissan', 'Urvan', 2022, 'Minibus', 'Diesel', 'Manuelle', 15, 550000, 70000, 3300000, 950000, '["15 Places","Climatisation","Radio/USB"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'standard', '["air_conditioning","usb_port","led_lights"]'::jsonb, 'TEST-CAT6-002', true, true, 'approved'),
(v_pid, v_ids[7], 'Bajaj Tricycle Cargo', 'Bajaj', 'RE Compact', 2023, 'Tricycle', 'Essence', 'Manuelle', 3, 80000, 10000, 480000, 150000, '["Économique","Cargo 500kg"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'basic', '["cargo_space","fuel_efficient"]'::jsonb, 'TEST-CAT7-001', true, true, 'approved'),
(v_pid, v_ids[7], 'TVS King Deluxe', 'TVS', 'King', 2022, 'Tricycle', 'Essence', 'Manuelle', 3, 75000, 9500, 450000, 140000, '["Économique","Cargo 450kg","Robuste"]'::jsonb, '["/placeholder.svg"]'::jsonb, 'Kinshasa', ARRAY['Kinshasa', 'Lubumbashi', 'Kolwezi'], 'basic', '["cargo_space","fuel_efficient"]'::jsonb, 'TEST-CAT7-002', true, true, 'approved');
END $$;